version: '3.8'

services:
  db:
    container_name: postgres-myportfolio
    image: postgres:latest
    environment:
      POSTGRES_DB: myportfolio
      POSTGRES_USER: allen
      POSTGRES_PASSWORD: th4l3nt4d3h4
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5002:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
